### ISSUE TITLE
Testing Reloader with Mosquitto

### ISSUE THREAD

**Issue by dystewart** [dystewart/openshift-deployment#5]
The final thing we need to do is update our Mosquitto deployment with annotations that Reloader uses to redeploy `pods` when a specified `configmap` or `secret` changes.
Check out the Reloader docs for more info on how it works: [Reloader](https://github.com/stakater/Reloader)

To track the `configmap` and `secret` resources of our Mosquitto `pod` we need to add the following annotations in the metadata section of the Mosquitto deployment.yaml:

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "mosquitto-secret-file"
    configmap.reloader.stakater.com/reload: "mosquitto-config-file"
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: quay.io/dystewar/mosquitto
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-conf
              mountPath: /mosquitto/config
            - name: mosquitto-secret
              mountPath: /mosquitto/secret  
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-config-file
        - name: mosquitto-secret
          secret:
            secretName: mosquitto-secret-file

```

Once you update the deployment.yaml manifest click save and finally we can check if our Reloader `pod` is working. At the web UI take a look at the secrets tab while in your Mosquitto project and select the mosquitto-secret-file resource. Take a look at the yaml of the secret resource and change the username or password to something else. As always click save to apply the changes. Now take a look back at your Reloader pod logs and you should see something like this:
![reloaderworks](https://user-images.githubusercontent.com/84931428/149165112-d2f6e104-6005-4b5e-8d3a-b21f538b8127.png)

The change was picked up by Reloader! if you look at the Mosquitto `pod` you'll see that it was just recreated to reflect the changes. This redeployment was triggered by Reloader! 

You can also test that changes to the Mosquitto `configmap` by making a change to the `configmap` yaml like below:
![false](https://user-images.githubusercontent.com/84931428/149166378-a207aa15-58a6-4ced-8179-746bb8b0885b.png)

Now looking back at the Reloader logs:
![cm](https://user-images.githubusercontent.com/84931428/149169071-f5c00d71-5609-45fd-8826-e767a62b323a.png)

Reloader detected our `configmap` changes too! And there you have it. We have successfully configured and deployed 2 applications in our OpenShift cluster! Most basic application deployments will be spun up in a similar way, and you can take what you've seen here to help with debugging your next deployment.
